export const rwanda = {
	receiverData:
		{
			fullName: 'Martin Wainstein',
			projectsActive: '2',
			currentEnergy: '845 kWh',
			allTimeEnergy: '10,150 MWh',
			wallet: '$604.25',
			autoReload: '28 days',
			notification: 'None',
			actionsReq: 'Confirm Auto-Pay',
		},
	project: {
		type: 'SOLAR ONLY',
		title: '5kW Solar at FabIDEAS Coop - Pilot 1',
		loc: 'Aibonito, Puerto Rico, USA',
		Stage: '3',
		investmentType: 'Grant',
		Issuer: '',
		category: "MUNI BOND",
		description: '5kW solar to be owned by the FabIDEAS Community Cooperative in Aibonito. The Coop is part of the Instituto Nueva Escuela (INE), and will host a Fab Lab manufacturing montessori school supplies.\n',
		bullets: [
			'Powering a unique social entrepreneurship model through a local cooperative',
			'Power purchase agreement tied to the standard local Aibonito tariff',
			'Pay-to-own solar model for the coop with all proceeds reinvested in the Fab Lab',
		],
		originator: 'Martin Wainstein',
		donated: '0',
		total: '4000',
		return: '0',
		benefit: '0',
		maturity: '2025',
		investBy: 'Jan 2020',
	},
};
