import React from 'react';
import SummaryCards from '../../../../General/SummaryCards/SummaryCards';
import AccountSummary from './AccountSummary/AccountSummary';
import SeeMore from "../../../../UI/SeeMore/SeeMore";
import InfoBoxTemplate from "../../../../General/InfoBoxTemplate/InfoBoxTemplate";

const InvestmentSummary = ({investor}) => {
	return (
		<React.Fragment>
			<div className="container investor-title">Your Investment Summary</div>
			<div className="investor-separator"/>
			<div className="investment-summary">
				<div className="container">
					<div className="row summary-cards">
						<div className="col-sm-6 col-lg-3 ">
							<SummaryCards
								title="your profile"
								items={[
									{value: investor["Your Profile"] && investor["Your Profile"].Name, desc: 'name'},
									{value: investor["Your Profile"] && investor["Your Profile"].Roles, desc: 'roles'}
								]}
								icon="beneficiary-icon"
							/>
						</div>
						<div className="col-sm-6 col-lg-3 ">
							<SummaryCards
								title="your investments"
								items={[
									{
										value: investor["Your Investments"] ? investor["Your Investments"]["Total Investments"] : 0,
										desc: 'total investments'
									},
									{
										value: investor["Your Investments"] ? investor["Your Investments"]["Projects Invested"] : 0,
										desc: 'projects invested'
									}
								]}
								icon="handout-icon"
							/>
						</div>
						<div className="col-sm-6 col-lg-3 ">
							<SummaryCards
								title="your returns"
								items={[
									{value: investor["Your Returns"] ? investor["Your Returns"]["Net Returns"] : '$0', desc: 'net returns'},
									{value: investor["Your Returns"] ? investor["Your Returns"]["RECs Received"] : 'MWh', desc: 'recs received'}
								]}
								icon="wallet-icon"
							/>
						</div>
						<div className="col-sm-6 col-lg-3 ">
							<SummaryCards
								title={
									<SeeMore
										infoContent={
											<InfoBoxTemplate
												title='ENERGY YOU FACILITATE'
												content={
													<div>
														My direct contributions’ refers to the sum of the energy generated by the projects but considering only the
														fraction corresponding to the percentage % of my investment relative to the total project cost.
														<br />
														<br />
														‘Total contributions’ is the sum of all energy generated by all projects I invested in, irrespective
														of how much I invested in each one.
													</div>
												}
											/>
										}>
										energy you facilitate
									</SeeMore>}
								items={[
									{value: investor["Energy You Facilitate"] ? investor["Energy You Facilitate"]["My Direct Contributions"] : 'KWh', desc: 'my direct contributions'},
									{value: investor["Energy You Facilitate"] ? investor["Energy You Facilitate"]["Total Contributions"] : 'KWh', desc: 'total contributions'}
								]}
								icon="solar-panel-icon"
								iconSize="30px"
								classes={["solar-icon-adjust"]}
							/>
						</div>
					</div>
					<AccountSummary
						investor={investor}
						usdbalance={investor.Balance ? investor.Balance.toFixed(2) : 0}
					/>
				</div>
			</div>
		</React.Fragment>
	)
};

export default InvestmentSummary;
